name: Daily Database Health Check

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1" # Using the version from your volta config
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run database health check
        env:
          ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
          ASTRA_DB_API_ENDPOINT: ${{ secrets.ASTRA_DB_API_ENDPOINT }}
        run: node --import=tsx src/scripts/dbHealthCheck.ts
